# Generated by Django 3.1 on 2020-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, upload_to='videos/images'),
        ),
    ]
