# Generated by Django 3.1 on 2020-09-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
