# Generated by Django 3.1 on 2020-09-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200921_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
    ]
